# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/SET253-15U.HCCMAIN/Documents/GitHub/ENES247Kamran/lab8-IntellectualProperty/lab8_2_1/Nexys4DDR_Master.xdc

# IP: ip/c_counter_binary_0/c_counter_binary_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_0 || ORIG_REF_NAME==c_counter_binary_0} -quiet] -quiet
