webtalk_init -webtalk_dir C:/Users/SET253-07U.HCCMAIN/Documents/GitHub/ENES247Kamran/lab7-Behavioral-Modeling/lab7_1_5/Counter/Counter.sim/sim_1/behav/xsim/xsim.dir/specific_counter_case_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May  2 15:45:53 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "08035c49-4b39-4a98-8892-74b6882a23bd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "88574e94954f4234b5eb2c0b355fbf89" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6300_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2170730681 -regid "" -xml C:/Users/SET253-07U.HCCMAIN/Documents/GitHub/ENES247Kamran/lab7-Behavioral-Modeling/lab7_1_5/Counter/Counter.sim/sim_1/behav/xsim/xsim.dir/specific_counter_case_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/SET253-07U.HCCMAIN/Documents/GitHub/ENES247Kamran/lab7-Behavioral-Modeling/lab7_1_5/Counter/Counter.sim/sim_1/behav/xsim/xsim.dir/specific_counter_case_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/SET253-07U.HCCMAIN/Documents/GitHub/ENES247Kamran/lab7-Behavioral-Modeling/lab7_1_5/Counter/Counter.sim/sim_1/behav/xsim/xsim.dir/specific_counter_case_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
